service: serverless

provider:
  name: aws
  runtime: nodejs12.x

functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - http:
          path: sendEmail
          method: post
          cors: true # <-- CORS!
